### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by onlyyou** [praschak/candelapy#4]
got this error on my pi 

`pi@raspberrypi:~/candelapy $ python candelapy.py F8:24:41:C0:38:43 100
WARNING: No module named pexpect
Traceback (most recent call last):
  File "candelapy.py", line 31, in <module>
    adapter.stop()
  File "/home/pi/.local/lib/python2.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 307, in stop
    self.disconnect(self._connected_device)
  File "/home/pi/.local/lib/python2.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 50, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 485, in disconnect
    if not self._receiver.is_set("disconnected"):
AttributeError: 'NoneType' object has no attribute 'is_set'
`

thanks

**Comment by sunkeunchoi** [comment]
Python 2.7.16

> got this error on my pi
> 
> `pi@raspberrypi:~/candelapy $ python candelapy.py F8:24:41:C0:38:43 100 WARNING: No module named pexpect Traceback (most recent call last): File "candelapy.py", line 31, in <module> adapter.stop() File "/home/pi/.local/lib/python2.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 307, in stop self.disconnect(self._connected_device) File "/home/pi/.local/lib/python2.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 50, in wrapper return func(self, *args, **kwargs) File "/home/pi/.local/lib/python2.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 485, in disconnect if not self._receiver.is_set("disconnected"): AttributeError: 'NoneType' object has no attribute 'is_set' `
> 
> thanks

I had same problem.

 Python 2.7.16

`pip install "pygatt[GATTTOOL]"` worked for me
